### ISSUE TITLE
Invoice Ninja 5.3

### ISSUE THREAD

**Issue by razor950** [mihai-cindea/invoiceninja_v5#1]
Hey, could the invoice ninja version be upgraded to latest? 5.3.x

the new requirement is PHP minimum requirements bumped from 7.3 to 7.4

**Comment by kiwimato** [comment]
Sorry, I somehow missed this issue. I just did, and for future reference, feel free to open PRs:
https://github.com/kiwimato/invoiceninja_v5/commit/cd63d25a0d4013e4ec96b4eeff4fe4f2116c022a
