### ISSUE TITLE
Failed: App\Jobs\Company\CompanyImport

### ISSUE THREAD

**Issue by Iceman248** [mihai-cindea/invoiceninja_v5#3]
I get this error when trying to import v5 data into this v5 Docker, using latest version, didn't work with previous version of v5 either.

Using JSON file, saw it was reported in the InvoiceNinja forums, some still had issues, was said to be resolved in 5.3.1, but it isn't for me. I had migrated from v4 to v5 hosted before trying to export and import to go self hosted.

**Comment by kiwimato** [comment]
This sounds like a bug in Invoice Ninja itself, can you raise an issue with them?
I know there's been some issues with importing data using JSON, not sure if it's this specific issue, but I know it will be released in 5.3.11.

**Comment by kiwimato** [comment]
@Iceman248 seems there was a new release, can you update your image and see if it fixes your issue?

**Comment by Iceman248** [comment]
Thanks. They were aware with some have mixed success at trying to rectify, so I figured it was worth a mention here.

The update did fix it! It seemed like it was a problem on the export side, as the file size after exporting from hosted platform was many times over the size from before and it imported just fine into this self hosted version.
