### ISSUE TITLE
SWAG config

### ISSUE THREAD

**Issue by luisalrp** [mihai-cindea/invoiceninja_v5#4]
Hello,

Could you provide an example of SWAG config? I am trying to do it work with swag+authelia using the swag dockermods "auto proxy". I think I am missing something because I can't make it work, while other unraid apps works perfect with swag+authelia label.

Here are the labels I configured.
![image](https://user-images.githubusercontent.com/31384138/144741424-582e9b48-dded-47e7-8ce0-c1d5a7e1d4a9.png)

Thanks!

**Comment by kiwimato** [comment]
Hey,

I'm not using SWAG for Invoice ninja but I'd be more than happy to help you with setting it up. I'm using SWAG with unifi controller, but not using the auto proxy thing. 

In this case I think you need to put the docker gateway IP which should be: 172.17.0.1 in "swag url" and in "swag port" better try the non encrypted port which in my case is 8545:
```
root@Rick:/mnt/disk3/docker/appdata/swag/nginx# docker ps | grep invoice
c59d368184ee   maihai/invoiceninja_v5:migrate             "docker-entrypoint /…"   2 weeks ago    Up 9 hours              9000/tcp, 0.0.0.0:8545->80/tcp, 0.0.0.0:8443->443/tcp                                                                              invoiceninja-v5

```

My non auto proxy config:
```
root@Rick:/mnt/disk3/docker/appdata/swag/nginx# cat proxy-confs/unifi.subdomain.conf
## Version 2021/05/18
# make sure that your dns has a cname set for unifi and that your unifi-controller container is not using a base url
# NOTE: If you use the proxy_cookie_path setting in proxy.conf you need to remove HTTPOnly;
# ex: proxy_cookie_path / "/; Secure";

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name unifi.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;

    # enable for Authelia
    #include /config/nginx/authelia-server.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /ldaplogin;

        # enable for Authelia
        #include /config/nginx/authelia-location.conf;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app 172.17.0.1;
        set $upstream_port 7080;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

        proxy_buffering off;
    }
}
root@Rick:/mnt/disk3/docker/appdata/swag/nginx# 
```

**Comment by luisalrp** [comment]
Tanks for your help. The main issue was I config it sleepy and instead of swag_address in key value I wrote "swag address". In the image I post it corrected in case someone needs it.
![image](https://user-images.githubusercontent.com/31384138/144753967-a45445c0-d047-4ab4-8a98-6c75126c0c59.png)

Here is the config regarding swag+authelia labels:
![image](https://user-images.githubusercontent.com/31384138/144754176-e762b4e9-e8ef-4ee8-873d-a88361abb276.png)

Now I am able to see the marvelous Authelia captive portal to introduce user and password and after login I get a 502 error. I'm one step closer to get it working.

**Comment by kiwimato** [comment]
Hmm I'm pretty sure you might have to try on a port different than 8443(I think 8545 as I mentioned in my previous comment is the default), because that will be a self signed certificate, so it may not work.
If that's not the case then you should check where this 502 is coming from, you should check invoiceninja docker logs

**Comment by luisalrp** [comment]
Thanks! I set as swag_port the container port, which is 80. I close the issue :)
